### ISSUE TITLE
Authorizer use display name instead role name

### ISSUE THREAD

**Issue by julienlusson** [uhm-coe/authorizer#62] opened 2018-10-22 12:14 UTC
Hi,

A nasty bug: Authorizer save the role display name in auth_settings_access_users_approved, instead of the role name. And if the display name contain a space, it doesn't work, after authentication, the user get a "no role" on the site.

Regards

**Comment by figureone** [comment] 2018-10-22 20:04
We run Authorizer in production on several servers with roles that have spaces in their display name, without any problems. Here's an example role:
```
global $wp_roles;
$subscriber = $wp_roles->get_role( 'subscriber' );
add_role( 'uh_member', 'UH Member', $subscriber->capabilities );
```
And the corresponding entry in `auth_settings_access_users_approved`:
```
Array
(
    [email] => someone@example.edu
    [role] => uh_member
    [date_added] => Jan 2017
)
```

Are you sure you're creating your roles properly? Maybe your role name itself has a space in it?
https://developer.wordpress.org/reference/functions/add_role/

**Comment by julienlusson** [comment] 2018-10-23 08:34
I've checked again on a brand new WordPress install corresponding to my use case of Authorizer:

1. Do a WordPress clean install
2. Create a Network
3. Install and activate Authorizer plugin on the network
4. Configure Authorizer (network wide)
5. Add a local WordPress User matching a CAS user.
6. Create a new site
7. Go the new site admin page
8. Install and activate "User role editor" plugin 
9. Go to the User role editor configuration
10. Duplicate the "editor" role (add new role, role name: "editorcopy", display role name: "copy of the editor role", Make copy of: editor)
11. Disable "User role editor" plugin
12. "Users" => "Add new" => "Add Existing User"
	1. Email => Choose the email of the existing user (step 5)
	2. Role => "editorcopy"
	3. "Skip Confirmation Email" => unchecked
	4. "Add existing user"
13. In an another browser (or Private session): validate the link received by email
14. Connect to the site admin page, authenticate with CAS:
	* Result: "Sorry, you are not allowed to access this page."
	* The user get "No role" on the site
	* auth_settings_access_users_approved in the DB: a:1:{i:0;a:4:{s:5:"email";s:20:"myuser@mydomain.test";s:4:"role";s:23:"copy of the editor role";s:10:"date_added";s:8:"Oct 2018";s:10:"local_user";b:1;}}

If you do the step 12 on an existing WP install, it'll do the same.

It'll work if the "Role Name" and the "Display name for role" are the same, for example: an English install of WP, but not with a French install!

**Comment by figureone** [comment] 2018-10-23 22:13
Thanks for the detailed steps to reproduce! We've confirmed it's a bug, and it's being caused by the `$role` param to the `invite_user` hook:
https://developer.wordpress.org/reference/hooks/invite_user/

This param is an array containing `name` and `capabilities`; Authorizer uses `name`, but it turns out that is the role's display name, not the role name. The role name is not available anywhere in the `invite_user` hook.

We'll get it fixed by doing a reverse lookup of the role name using the display name. Thanks!

(Researching the issue, in WordPress core, there is an object representation of a role, and an array representation. They both have a `name` attribute, but the meaning differs. `$role->name` is the name of the role, but `$role['name']` is the display name of the role.)

**Closed** 2018-10-23 22:16 UTC

**Comment by figureone** [comment] 2018-10-23 22:19
Version 2.8.4 just released with the fix.
