### ISSUE TITLE
CAS connection reverts role intermittently

### ISSUE THREAD

**Issue by lukeislucas** [uhm-coe/authorizer#93] opened 2020-04-01 23:39 UTC
I am having an issue where users are reporting their roles are being reverted and it would appear to be related to the authorizer plugin. Since there are no reported cases of this happening, I am thinking perhaps there is a plugin conflict, but I am unsure where to look.

Is there a specific block or page that may be worth checking out? Has anyone else had this issue with a `SAML_VERSION_1_1` CAS Server?

**Comment by figureone** [comment] 2020-04-28 19:17
Aloha, please check the conversation here and let us know if any of those scenarios match, or if you have other thoughts:
https://wordpress.org/support/topic/roles-changing-on-login

**Comment by RobertATVT** [comment] 2020-09-24 17:44
I'm having the same issue with one of my users. I approved her as an editor in Authorizer and she reverted to subscriber the next time she logged in. So I changed her role via the wordpress user list and she logged in as editor fine, the next time she logged in she was a subscriber again. I looked at the conversation you linked above and I'm not sure if any of those situations apply, though the problem persists. We aren't using any additional plugins that change roles either.

**Comment by figureone** [comment] 2020-09-24 18:17
Very strange. Some follow-up questions:
1. How many total users do you have?
1. Can you verify that there's not actually 2 separate WordPress accounts for this user, one as editor and one as subscriber?
1. Can you provide more detail on the steps you described? Sounds like: they logged in and went on the Pending Users list; you set their role to `Editor` and approved them; they logged in again and had a role of `Subscriber`; you changed role to `Editor` via WordPress Edit User; they logged in again and had a role of `Editor`; sometime later they logged in again and had a role of `Subscriber`.
1. I'm assuming `Subscriber` is the default role set in Authorizer Settings?
1. Can you share the rest of your Authorizer Settings? (No need to share the External Service details; just indicate which one you are using.)
1. Can you provide a list of other activated plugins?

Also, just in case, can you search your active theme code for any `wp_update_user()` or `set_role()` calls that might be editing user roles elsewhere.
https://developer.wordpress.org/reference/functions/wp_update_user/
https://developer.wordpress.org/reference/classes/wp_user/set_role/

**Comment by RobertATVT** [comment] 2020-09-24 18:34
1. 230 Users
2. Only one account
3. Those are pretty much exactly what happens. Initially, I set her up with editor through authorizer, she logged in okay and then the next time when she logged in she was reset to subscriber (authorizer default). Then I went into WP-Admin->Users and set her role manually to Editor. She logged in fine, made changes, then the next time she logged in she was a subscriber again. Wash, rinse, repeat.
4. Correct
5. Settings are: 
Default User Role: Subscriber
Only CAS Login
CAS Automatic Login checked
6. Plugins
Admin Menu Editor
Advanced Custom Fields
Custom 404
Custom Post Type UI
Duplicate Page
Google Analytics Dashboard
Groups
Header and Footer Scripts
PDF Embedder
Plugin Organizer
Reveal IDs
Shortcodes Ultimate
Simple Page Sidebars
SVG Support
Visual Composer Add-On - Expand Grid
Wider Admin Menu
Wordfence Security
WPBakery Page Builder

Those functions aren't used by the theme

**Comment by figureone** [comment] 2020-09-24 19:12
Thanks! We'll try to see if we can set up a test environment to reproduce. Might be some specific edge case we're missing, but it for sure should not do that. :)

**Comment by pkarjala** [comment] 2020-09-24 19:18
@RobertATVT To assist, can you please let us know the versions of Authorizer and WordPress you are using?

**Comment by RobertATVT** [comment] 2020-09-24 19:27
The latest version of both wordpress and authorizer

**Comment by pkarjala** [comment] 2020-09-24 19:31
To verify, that is WordPress 5.5.1 and Authorizer 2.10.0?

**Comment by RobertATVT** [comment] 2020-09-24 19:36
Correct

**Comment by pkarjala** [comment] 2020-09-24 20:38
One more thing--is this a single site or multi-site install?

**Comment by RobertATVT** [comment] 2020-09-25 12:29
Single 

Update first and last name fields at login
Automatic Login is checked
Linked by username is unchecked

**Comment by pkarjala** [comment] 2020-09-25 20:41
Thanks!  We've done some testing and have been unable to reproduce this issue in our test environment.

If possible, could you please try one of the following:

1. Disable a single plugin at a time in your setup, test the issue, and see if it continues to occur.  You will need to do this individually for each plugin on your install.  Advanced Custom Fields is not likely to be an issue so can be skipped.

2. Set up a fresh WordPress 5.5.1 install, set up Authorizer 2.10.0, and configure it for your CAS environment, and then test the same workflow to see if the issue is reproducible.  Please do not install any other themes or plugins on this setup.

**Comment by figureone** [comment] 2020-09-25 21:21
Any chance your CAS server returns multiple emails for a user, or mixed case emails (e.g., `UserName@example.edu`)? It's possible that the lookup in the Approved User list isn't successful because the cases don't match, so it's reverting to the default role when it tries to insert the "new" user.

**Comment by lukeislucas** [comment] 2021-05-14 14:04
Paul, I see that you had responded to something similar [here](https://wordpress.org/support/topic/roles-changing-on-login/).

For us, the solution appears to be editing the user via the `user-edit.php` page as you instructed. It appears that the `user_profile_update_errors` hook is not being hit when editing a users role via `users.php` page.

I am sharing since this may be the cause for several others too.

**Comment by figureone** [comment] 2021-05-14 17:47
Oh interesting, perhaps WordPress core changed some of the hook behavior. I remember there being several user update hooks that were different between multisite and single site environments. Thanks for the sleuthing, we'll take a look!

**Comment by figureone** [comment] 2021-05-19 01:32
Ok, I've tested internally and I think you've nailed the cause of this issue.

WordPress doesn't give us much to work with in the code path for changing user roles from `users.php` (via the checkboxes next to users in the list and the _Change role to..._ dropdown next to bulk actions). It pretty much directly calls `WP_User::set_role()` and bypasses the other hooks that Authorizer uses to sync roles.

I'm working on a fix, right now the problem is that Authorizer uses `set_role()` itself internally and I need to do some testing to ensure that I don't trigger a case where roles are repeatedly changed. `WP_User::set_role()` does include an action hook, `set_user_role`, so that's what I plan on using to address this.

Will keep you updated! Thanks again for narrowing this one down.

**Comment by figureone** [comment] 2021-05-19 21:18
Aloha, issue should be fixed here: https://github.com/uhm-coe/authorizer/commit/5055bc9735fbb339d12a82d1a2f0151290fa09a4

This will be included in the next release, but feel free to pull from github (master branch) if you want to get a head start on testing. Thanks again for discovering this!

**Closed by figureone** 2021-05-19 21:18 UTC
