### ISSUE TITLE
Private blog posts not protected

### ISSUE THREAD

**Issue by InvisibleMass** [uhm-coe/authorizer#42] opened 2017-09-29 16:09 UTC
Wordpress 4.8.2; Theme: Twenty Seventeen, Version: 1.3; Plugins other than Authorizer: none
Permalinks: .../2017/09/29/sample-post/
Authorizer Version 2.6.21; LDAP logins; Login access: Only approved users; Public access: Only logged in users;
![image](https://user-images.githubusercontent.com/32394972/31023683-ec6683e0-a53c-11e7-8d7f-b6481729a76e.png)

Using this rather simple setup on an almost-virgin standard Wordpress default installation with a freshly restarted browser (Firefox) with a cleaned cache and no stored passwords:

- all blog posts and related comments are accessible using a direct link like .../2017/09/29/sample-post/
- all blog posts are accessible from a homepage section that is linked to the blog
- all blog posts are accessible via previous/next links from other blog posts
- files in the media library are accessible using a direct link like .../wp-content/uploads/2017/09/testzip1.zip
- files in the media library are accessible via e.g. a link in a blog post (that should not be accessible either)

Note that all Posts are explicitly listed in the Private Pages list of Authorizers Public access tab.
Protection works on:
- pages not listed in the Public pages list, including the Blog page itself
- accesses to the blog via e.g. .../category/uncategorized/
- accesses to the blog via e.g. .../tag/xyz/

The intention of course is to restrict access to all blog posts and files in the media library.

Where am I going wrong?

**Comment by InvisibleMass** [comment] 2017-10-06 17:26
Is anybody investigating this issue?
It seems like a pretty fundamental failure to me. I am surprised that it does not draw any attention.
If this is likely a setup problem, let me know! I reviewed all available information on the plugin but could not identify any setup errors.

**Comment by pkarjala** [comment] 2017-10-06 17:28
@InvisibleMass Apologies; we have seen your bug report, but have been completely swamped with other responsibilities.  We're going to return to and start working through the bug reports this coming week.

**Comment by figureone** [comment] 2017-10-07 02:33
Looks like a regression in the detection of 404 pages, I think here:
https://github.com/uhm-coe/authorizer/commit/dcb862c43d00e500e95a085e41d8658a5b164213

We'll get this one fixed quickly and deploy a new version. Thanks!

**Comment by figureone** [comment] 2017-10-11 00:24
The regression was actually here, on Jun 5 2017:
https://github.com/uhm-coe/authorizer/commit/1cba9f3f7f77c973a1ccc8d06c9fe1bfcf0a624c

**Comment by figureone** [comment] 2017-10-11 01:13
Fixed here, and will be included in the next release (version 2.6.22):
https://github.com/uhm-coe/authorizer/commit/8a3366b7b72c8006c9f29aa86e20c3cc66669e0d

Thanks for finding the bug!

As an aside, note that this plugin does not block access to raw files (e.g., images, uploads, css/js resources, since these files are served directly by the web server, with no involvement from WordPress). We've set up sites in the past with workarounds, so let us know if you want some ideas.

Also note that the plugin does not prevent private pages from being exposed on public pages that might link to them, as this would be resource intensive. Please deal with that situation directly in the template files used on the pages you mark public.

**Closed by figureone** 2017-10-11 01:13 UTC
Labels: bug

**Comment by InvisibleMass** [comment] 2017-10-11 12:36
The statement

> "the plugin does not prevent private pages from being exposed on public pages that might link to them"

is confusing me.
What kind of links or circumstances does this refer to?
I think these limitations should be documented (also the raw file access issue)!
Plugin users should get comprehensive information about what is protected and what not.

**Comment by figureone** [comment] 2017-10-11 22:08
I think it's pretty straightforward. The plugin can be configured to prevent access to a WordPress site unless you are logged in. You have the choice of making certain posts/pages "public" when configured this way. It's up to you to verify that those "public" pages do not release any potentially private information. There's no way for the plugin to cover all ways you might add other content (you can link directly to it, you can create your own queries, you can create menus, etc.).

Raw file access is basic knowledge about web servers. WordPress also allows you to offload file uploads to, e.g., S3 buckets, so there's no one solution to prevent access. What we've done in the past (and this is a little convoluted) is to drop an `.htaccess` file into the uploads directory that redirects all requests to a non-existent page (say "/DirectAccessToFilesDenied"). Now, since this doesn't exist, the web server will pass it on to WordPress, and WordPress will try to render a 404 page. We can now hook into `parse_request`, check if `REQUEST_URI` points to something in the uploads directory, and do a permissions check before serving the file, or bailing with an error message.

Anyway, If you see a good spot for extra documentation, please submit a pull request! The docs are a little stale at this point, your situation might be a addition to the "Frequently Asked Questions" section of readme.txt
